HealthCare.Presentaion/Controllers/AppointmentController.cs
using HealthCare.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HealthCare.Presentaion.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly IAppointmentServices _services;
        public AppointmentController(IAppointmentServices appointmentServices)
        {
            _services = appointmentServices;
        }
        public async Task<IActionResult> GetAllByDay(int doctorID, DateTime day)
        {
            var model = await _services.GetAllByDay(doctorID, day);
            return View("GetAllAppointmentsForThatDay", model);
        }
        public async Task<IActionResult> GetPrevious(int doctorID)
        {
            var all = await _services.GetAllByDoctorId(doctorID);
            var model = all.Where(a => a.DateTime.Day < DateTime.Now.Day).ToList();
            return View("GetAllAppointmentsForThatDay", model);
        }
        public async Task<IActionResult> GetUpcomming(int doctorID)
        {
            var all = await _services.GetAllByDoctorId(doctorID);
            var model = all.Where(a => a.DateTime.Day > DateTime.Now.Day).ToList();

            return View("GetAllAppointmentsForThatDay", model);
        }

        [Authorize(Roles = "Doctor")]
        public async Task<IActionResult> CompletedAppointment(int Id)
        {

            await _services.CompletedAppointment(Id);
            return RedirectToAction("Create", "MedicalRecord", new { id = Id });
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> PatientAppointments(int ID)
        {
            var model = await _services.GetByPatientId(ID);
            model = model.OrderByDescending(a => a.DateTime).ToList();
            return View(model);

        }
        public async Task<IActionResult> CancleAppointment(int Id)
        {
            await _services.CancleAppointment(Id);
            return RedirectToAction(nameof(PatientAppointments), new { id = User.Claims.FirstOrDefault(c => c.Type == "PatientId").Value });
        }
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> BookNewAppointment(int timeslotId, int patientId)
        {
            await _services.BookAppointment(timeslotId, patientId);
            return RedirectToAction("PatientAppointments", new { ID = patientId });
        }
    }
}

HealthCare.Presentaion/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace HealthCare.Presentaion.Controllers
{
    public class ProfileController : Controller
    {

        public IActionResult Index()
        {
            if (User.IsInRole("Patient"))
            {
                return RedirectToAction("Edit", "Patient", new { id = User.Claims.FirstOrDefault(c => c.Type == "PatientId")?.Value });
            }
            else
            {
                return RedirectToAction("Edit", "Doctor", new { id = User.Claims.FirstOrDefault(c => c.Type == "DoctorId")?.Value });

            }
        }
    }
}

HealthCare.Presentaion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] HealthCare</title>

    <!-- Bootstrap CSS and other styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/icofont.css">
    <link rel="stylesheet" href="~/css/slicknav.min.css">
    <link rel="stylesheet" href="~/css/owl-carousel.css">
    <link rel="stylesheet" href="~/css/datepicker.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/normalize.css">
    <link rel="stylesheet" href="~/css/styleM.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <link rel="stylesheet" href="~/HealthCare.Presentaion.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
        html, body {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        main {
            flex: 1;
        }

        footer {
            background-color: #0a4275;
            margin-top: auto;
            width: 100%;
        }
    </style>
</head>
<body>
    @await Html.PartialAsync("_Navbar.cshtml")

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="text-center text-white p-1" style="background-color :#3c74b0">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2024 Copyright:
            <a class="text-white" >Bug Hunters Team ITI</a>
        </div>
    </footer>

    <!-- JavaScript files -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/easing.js"></script>
    <script src="~/js/colors.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.nav.js"></script>
    <script src="~/js/slicknav.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/tilt.jquery.min.js"></script>
    <script src="~/js/owl-carousel.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/steller.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HealthCare.Presentaion/Views/Shared/_Navbar.cshtml
@using System.Security.Claims
<header>
    <nav class="navbar navbar-expand-lg navbar-dark shadow-sm" style="background-color:#3b73af">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <h2 class="mb-0 text-white">Medicnova</h2>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
                <div class="navbar-nav text-center" style="margin:0 auto" id="NavElements">
                    <a asp-action="Index" asp-controller="Doctor" class="nav-link text-white fs-6 mx-3">
                        <i class="fas fa-user-md"></i>
                        <span>Doctors</span>
                    </a>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Doctor"))
                        {
                            <a asp-action="GetAllByDay" asp-controller="Appointment" asp-route-day="@DateTime.Now" asp-route-doctorID="@User.Claims.FirstOrDefault(c => c.Type == "DoctorId")?.Value" class="nav-link text-white fs-6 mx-3">
                                <i class="fas fa-calendar-check"></i>
                                <span>Appointments</span>
                            </a>
                            <a asp-action="ViewDoctorMedicalRecords" asp-controller="MedicalRecord" asp-route-Id="@User.Claims.FirstOrDefault(c => c.Type == "DoctorId")?.Value" class="nav-link text-white fs-6 mx-3">
                                <i class="fas fa-file-medical"></i>
                                <span>Medical Records</span>
                            </a>
                            <a asp-action="AddTimeSlot" asp-controller="Doctor" asp-route-DoctorId="@User.Claims.FirstOrDefault(c => c.Type == "DoctorId")?.Value" class="nav-link text-white fs-6 mx-3">
                                <i class="fas fa-clock"></i>
                                <span>Add Time Slot</span>
                            </a>
                        }
                        else if (User.IsInRole("Patient"))
                        {
                            <a asp-action="PatientAppointments" asp-controller="Appointment" asp-route-Id="@User.Claims.FirstOrDefault(c => c.Type == "PatientId")?.Value" class="nav-link text-white fs-6 mx-3">
                                <i class="fas fa-calendar-alt"></i>
                                <span>Appointments</span>
                            </a>
                            <a asp-action="ViewPatientMedicalRecords" asp-controller="MedicalRecord" asp-route-Id="@User.Claims.FirstOrDefault(c => c.Type == "PatientId")?.Value" class="nav-link text-white fs-6 mx-3">
                                <i class="fas fa-notes-medical"></i>
                                <span>Medical Records</span>
                            </a>
                        }
                    }
                </div>
                <div class="navbar-nav mx-3 d-flex align-items-center">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="navbar-text text-light fs-6 mx-3">@User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value</span>

                        <div class="dropdown mx-3">
                            <a class="text-white fs-6" href="#" id="notificationDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-bell"></i>
                                <span id="notificationCount" class="badge bg-danger position-absolute top-0 start-100 translate-middle">0</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationDropdown" id="notificationList">
                                <!-- Notifications will be dynamically loaded here -->
                            </ul>
                        </div>

                        <!-- Settings Dropdown -->
                        <div class="dropdown mx-3">
                            <a class="text-white fs-6" href="#" id="settingsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-cog"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" style="width:150px;" aria-labelledby="settingsDropdown">
                                <li><a asp-action="Index" asp-controller="Profile" class="dropdown-item"><i class="fas fa-user me-2"></i> Profile</a></li>
                                <li><a asp-action="Logout" asp-controller="Account" class="dropdown-item"><i class="fas fa-sign-out-alt me-2"></i> Logout</a></li>
                            </ul>
                        </div>
                    }
                    <div>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a asp-action="Login" asp-controller="Account" class="btn btn-light me-2" id="LogInBtn">Login</a>
                            <a asp-action="Register" asp-controller="Account" class="btn btn-success me-4" id="RegBtn">Register</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        function loadNotifications() {
            $.ajax({
                url: '/Notification/GetUserNotifications',
                type: 'GET',
                success: function (data) {
                    var notificationList = $('#notificationList');
                    notificationList.empty();

                    if (data.length > 0) {
                        $('#notificationCount').text(data.length);
                        $.each(data, function (index, notification) {
                            notificationList.append('<li  style="background-color:#c9d9ee;"><a class="dropdown-item" href="#">' + notification.title + '<br/><small>' + notification.message + '</small></a></li><hr>');
                        });
                    } else {
                        notificationList.append('<li><a class="dropdown-item" href="#">No new notifications</a></li>');
                    }
                }
            });
        }

        loadNotifications();

        setInterval(loadNotifications, 60000);
    });
</script>

<style>
    .dropdown-menu {
        max-height: 300px;
        overflow-y: auto;
        width: 300px;
    }

    .dropdown-item {
        white-space: normal;
        padding: 10px;
    }

    .nav-link {
        display: flex;
        flex-direction: column;
        align-items: center;
        transition: background-color 0.3s, color 0.3s;
        padding: 5px 10px;
    }

        .nav-link:hover, .btn:hover {
            background-color: #1E88E5;
            color: #fff;
            border-radius: 7px;
        }

    .fas {
        font-size: 1.3rem;
    }

    .nav-link span {
        font-size: 0.8rem;
    }

    .navbar-brand h2 {
        font-size: 1.5rem;
    }

    /* Adjusting notification badge position */
    #notificationCount {
        font-size: 0.8rem;
        padding: 4px;
        border-radius: 50%;
    }
</style>

HealthCare.Presentaion/Views/Shared/logInLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/SignStyle.css" />
    <title>Login</title>
</head>
<body>
    @RenderBody()
    @RenderSection("Scripts", required: false)
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>